version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"

  mongo:
    image: mongo:4.2
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: son
      MONGO_INITDB_ROOT_PASSWORD: schoolofnet
      MONGO_INITDB_DATABASE: restfulapi
    ports:
      - 27017:27017  
